### ISSUE TITLE
Store#clear does not set initial state from ES6 class constructor 

### ISSUE THREAD

**Issue by oyvinmar** [martyjs/marty#356] opened 2015-07-02 07:20 UTC
When I set the initial state via ES6 class constructor:

```javascript
class MyStore extends Marty.Store {
  constructor(...args) {
    super(...args);
    this.state = new Immutable.List();
  }
}
```

And then call Store#clear() the state is set to the default `getInitalState()` and not `new Immutable.List`. I'm currently using `getInitialState` in my ES6 classes as workaround.

**Comment by taion** [comment] 2015-07-02 14:04
Duplicate of https://github.com/martyjs/marty-lib/issues/24. Going to close this issue in favor of that one, because it has more discussion on it already.

**Closed by taion** 2015-07-02 14:04 UTC
